version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - 3306:3306
    volumes:
      - "./scripts/Minitok.sql:/docker-entrypoint-initdb.d/1_Minitok.sql"
    environment:
      - MYSQL_DATABASE=Minitok
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_RANDOM_ROOT_PASSWORD="yes" 
  minio:
    image: 'minio/minio:latest'
    ports:
      - 9000:9000
    volumes:
      - "/data/minio:/data/minio"
    command: "server /data/minio"
  redis:
    image: 'redis'
    ports:
      - 6379:6379
    volumes:
      - ./scripts/redis.conf:/etc/redis/redis.conf
    environment:
      - vm.overcommit_memory=1
    command: "redis-server /etc/redis/redis.conf"
  minitok:
    build: 
      context: .
      dockerfile : ./Dockerfile
    ports:
     - "8080:8080"
    volumes:
      - ./scripts/wait-for.sh:/apps/wait-for.sh
    depends_on:
      - mysql
      - minio
      - redis
    command: ["./wait-for.sh", "mysql:3306","--", "/apps/Minitok" ]